{
 "title": "SFPTPd",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sfptpd_time", "legendFormat": "{{ exported_instance }}" }
   ]
  },
  {
   "title": "Master Clock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sfptpd_master", "legendFormat": "{{ exported_instance }}" }
   ]
  },
  {
   "title": "Slave Clock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sfptpd_slave", "legendFormat": "{{ exported_instance }}" }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sfptpd_last_update", "legendFormat": "{{ exported_instance }}" }
   ]
  },
  {
   "title": "Disciplining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sfptpd_is_disciplining", "legendFormat": "{{ exported_instance }}" }
   ]
  },
  {
   "title": "In Sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sfptpd_in_sync", "legendFormat": "{{ exported_instance }}" }
   ]
  },
  {
   "title": "Alarms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sfptpd_alarms", "legendFormat": "{{ exported_instance }}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Offset",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "sfptpd_offset", "legendFormat": "{{ exported_instance }}" }
   ]
  },
  {
   "title": "PID Gains",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 9 },
   "targets": [
    { "expr": "sfptpd_pterm", "legendFormat": "{{ exported_instance }} P" },
    { "expr": "sfptpd_iterm", "legendFormat": "{{ exported_instance }} I" }
   ]
  },
  {
   "title": "Frequency Adjust",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "sfptpd_freq_adj", "legendFormat": "{{ exported_instance }}" }
   ]
  }
 ]
}